on: [push, pull_request]

name: CI

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: v14.x
      - name: Install dependencies
        run: npm install
      - name: Check linting
        run: npm run lint

  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 13.x, 14.x]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        if: runner.os != 'Linux'
        run: npm install --omit=peer
      - name: Install Dependencies Linux
        if: runner.os == 'Linux'
        # Manually installing peer dependencies until NPM v7+ flags start working
        run: npm install --include=peer && npm i nice-napi@^1.0.2
      - name: Test
        run: npm test
